routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('landing');
});
Route::get('admin', function () {
    return view('admin2/admin-home');
});
Route::get('admin-hajatan', function () {
    return view('admin2/admin-hajatan');
});
Route::get('admin-chat', function () {
    return view('admin2/admin-chat');
});
// Route::get('/coba', function () {
//     return view('coba');
// });
// Route::get('/home', function () {
//     return view('home');
// });
// Route::get('/login', function () {
//     return view('login');
// });
Route::get('/register', function () {
    return view('register');
});
Route::get('/tmagangpadi', function () {
    return view('tmagangpadi');
});
Route::get('/tmaganguang', function () {
    return view('tmaganguang');
});
// Route::get('/tmagangberas', function () {
//     return view('tmagangberas');
// });
Route::get('/thutangberas', function () {
    return view('tmaganguang');
});
Route::get('/thutangpadi', function () {
    return view('thutangpadi');
});
Route::get('/thutanguang', function () {
    return view('thutanguang');
});
// Route::get('/tkeluarberas', function () {
//     return view('tkeluarberas');
// });
// Route::get('/tkeluarpadi', function () {
//     return view('tkeluarpadi');
// });
Route::get('/tkeluaruang', function () {
    return view('tkeluaruang');
});
// Route::resource('input', DataTamuController::class);

Route::get('/magangberas', function () {
    return view('Anggota/m_beras');
});
Route::get('/magangpadi', function () {
    return view('Anggota/m_padi');
});
Route::get('/maganguang', function () {
    return view('Anggota/m_uang');
});
Route::get('/hutangberas', function () {
    return view('Anggota/h_beras');
});
Route::get('/hutangpadi', function () {
    return view('Anggota/h_padi');
});
Route::get('/hutanguang', function () {
    return view('Anggota/h_uang');
});
// Route::get('/keluarberas', function () {
//     return view('Anggota/k_beras');
// });
// Route::get('/keluarpadi', function () {
//     return view('Anggota/k_padi');
// });
// Route::get('/k_uang', function () {
//     return view('Anggota/k_uang');
// });
Route::get('/chat', function () {
    return view('Anggota/chat');
});



Route::resource('tambahtamu', 'DataTamuController');
Route::resource('home', 'DataTamu2Controller');
// Route::resource('edit', 'DataTamu2Controller');
Route::resource('edittamu', 'DataTamu2Controller');
Route::resource('tkeluarberas', 'MagangKeluarBerasController');
Route::resource('tkeluarpadi', 'MagangKeluarPadiController');
Route::resource('tkeluaruang', 'MagangKeluarUangController');
Route::resource('k_beras', 'ReadMagangBerasController');
Route::resource('k_padi', 'ReadMagangPadiController');
Route::resource('k_uang', 'ReadMagangUangController');
Route::resource('editmagangberas', 'MagangKeluarBerasController');
Route::resource('editmagangpadi', 'MagangKeluarPadiController');
Route::resource('editmaganguang', 'MagangKeluarUangController');
Route::resource('tmagangberas', 'TambahMagangBerasController');
Route::resource('tmagangpadi', 'TambahMagangPadiController');
Route::resource('tmaganguang', 'TambahMagangUangController');
Route::resource('thutangberas', 'TambahHutangBerasController');
Route::resource('thutangpadi', 'TambahHutangPadiController');
Route::resource('thutanguang', 'TambahHutangUangController');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/editmagangberas.blade.php
@extends('layouts.main')
@section('content')
<div class="main-panel">        
    <div class="content-wrapper">
      <div class="row">
        <div class="col-md-6 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <h4 class="card-title">Edit Magang Beras</h4>
              
                <form action="{{ route('editmagangberas.update', $keluar_magang_beras->id) }}"  method="POST">
                  @csrf
                  @method('PUT')
                <form class="forms-sample">
                  <div class="form-group">
                    <label for="nama">Nama</label>
                    <input type="string" class="form-control" id="nama" name="nama"  value="<?php echo $keluar_magang_beras['nama']; ?>"placeholder="Nama">
                  </div>
                  <div class="form-group">
                    <label for="alamat">Alamat</label>
                    <input type="string" class="form-control" id="alamat" name="alamat" value="<?php echo $keluar_magang_beras['alamat']; ?>"placeholder="Alamat">
                  </div>
                  <div class="form-group">
                    <label for="no_hp">NO HP</label>
                    <input type="char" class="form-control" id="no_hp" name="no_hp" value="<?php echo $keluar_magang_beras['no_hp']; ?>" placeholder="NO HP">
                  </div>
                  <div class="form-group">
                    <label for="tgl">Tanggal</label>
                    <input type="date" class="form-control" id="tgl" name="tgl" value="<?php echo $keluar_magang_beras['tgl']; ?>"placeholder="tgl">
                  </div>
                  <div class="form-group">
                    <label for="nominal">Nominal</label>
                    <input type="int" class="form-control" id="nominal" name="nominal" value="<?php echo $keluar_magang_beras['nominal']; ?>"placeholder="nominal">
                  </div>
                  <button type="submit" class="btn btn-primary me-2">Simpan</button>
                  <button class="btn btn-light">Cancel</button>
                </form>
            </div>
          </div>
        </div>
@endsection

resources/views/editmagangpadi.blade.php
@extends('layouts.main')
@section('content')
<div class="main-panel">        
    <div class="content-wrapper">
      <div class="row">
        <div class="col-md-6 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <h4 class="card-title">Edit Magang Padi</h4>
              
                <form action="{{ route('editmagangpadi.update', $keluar_magang_padi->id) }}"  method="POST">
                  @csrf
                  @method('PUT')
                <form class="forms-sample">
                  <div class="form-group">
                    <label for="nama">Nama</label>
                    <input type="string" class="form-control" id="nama" name="nama"  value="<?php echo $keluar_magang_padi['nama']; ?>"placeholder="Nama">
                  </div>
                  <div class="form-group">
                    <label for="alamat">Alamat</label>
                    <input type="string" class="form-control" id="alamat" name="alamat" value="<?php echo $keluar_magang_padi['alamat']; ?>"placeholder="Alamat">
                  </div>
                  <div class="form-group">
                    <label for="no_hp">NO HP</label>
                    <input type="char" class="form-control" id="no_hp" name="no_hp" value="<?php echo $keluar_magang_padi['no_hp']; ?>" placeholder="NO HP">
                  </div>
                  <div class="form-group">
                    <label for="tgl">Tanggal</label>
                    <input type="date" class="form-control" id="tgl" name="tgl" value="<?php echo $keluar_magang_padi['tgl']; ?>"placeholder="tgl">
                  </div>
                  <div class="form-group">
                    <label for="nominal">Nominal</label>
                    <input type="int" class="form-control" id="nominal" name="nominal" value="<?php echo $keluar_magang_padi['nominal']; ?>"placeholder="nominal">
                  </div>
                  <button type="submit" class="btn btn-primary me-2">Simpan</button>
                  <button class="btn btn-light">Cancel</button>
                </form>
            </div>
          </div>
        </div>
@endsection

resources/views/editmaganguang.blade.php
@extends('layouts.main')
@section('content')
<div class="main-panel">        
    <div class="content-wrapper">
      <div class="row">
        <div class="col-md-6 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <h4 class="card-title">Edit Magang Uang</h4>
              
                <form action="{{ route('editmaganguang.update', $keluar_magang_uang->id) }}"  method="POST">
                  @csrf
                  @method('PUT')
                <form class="forms-sample">
                  <div class="form-group">
                    <label for="nama">Nama</label>
                    <input type="string" class="form-control" id="nama" name="nama"  value="<?php echo $keluar_magang_uang['nama']; ?>"placeholder="Nama">
                  </div>
                  <div class="form-group">
                    <label for="alamat">Alamat</label>
                    <input type="string" class="form-control" id="alamat" name="alamat" value="<?php echo $keluar_magang_uang['alamat']; ?>"placeholder="Alamat">
                  </div>
                  <div class="form-group">
                    <label for="no_hp">NO HP</label>
                    <input type="char" class="form-control" id="no_hp" name="no_hp" value="<?php echo $keluar_magang_uang['no_hp']; ?>" placeholder="NO HP">
                  </div>
                  <div class="form-group">
                    <label for="tgl">Tanggal</label>
                    <input type="date" class="form-control" id="tgl" name="tgl" value="<?php echo $keluar_magang_uang['tgl']; ?>"placeholder="tgl">
                  </div>
                  <div class="form-group">
                    <label for="nominal">Nominal</label>
                    <input type="int" class="form-control" id="nominal" name="nominal" value="<?php echo $keluar_magang_uang['nominal']; ?>"placeholder="nominal">
                  </div>
                  <button type="submit" class="btn btn-primary me-2">Simpan</button>
                  <button class="btn btn-light">Cancel</button>
                </form>
            </div>
          </div>
        </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/login.blade.php
{{-- <!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Star Admin2 </title>
  <!-- plugins:css -->
  <link rel="stylesheet" href="assets/vendors/feather/feather.css">
  <link rel="stylesheet" href="assets/vendors/mdi/css/materialdesignicons.min.css">
  <link rel="stylesheet" href="assets/vendors/ti-icons/css/themify-icons.css">
  <link rel="stylesheet" href="assets/vendors/typicons/typicons.css">
  <link rel="stylesheet" href="assets/vendors/simple-line-icons/css/simple-line-icons.css">
  <link rel="stylesheet" href="assets/vendors/css/vendor.bundle.base.css">
  <!-- endinject -->
  <!-- Plugin css for this page -->
  <!-- End plugin css for this page -->
  <!-- inject:css -->
  <link rel="stylesheet" href="assets/css/vertical-layout-light/style.css">
  <!-- endinject -->
  <link rel="shortcut icon" href="assets/images/favicon.png" />
</head>

<body>
  <div class="container-scroller">
    <div class="container-fluid page-body-wrapper full-page-wrapper">
      <div class="content-wrapper d-flex align-items-center auth px-0">
        <div class="row w-100 mx-0">
          <div class="col-lg-4 mx-auto">
            <div class="auth-form-light text-left py-5 px-4 px-sm-5">
              <h4>SI KONDANG</h4>
                <form class="pt-3">
                  <form method="POST" action="{{ route('login') }}">
                    @csrf

                    <div class="form-group row">
                                    
                      <div class="col-md-10 offset-md-1">
                          <input id="email" type="email" name ="email "class="form-control @error('email') is-invalid @enderror"  value="{{ old('email') }}" required autocomplete="email" autofocus placeholder="E-Mail">
                          
                          @error('email')
                          <span class="invalid-feedback" role="alert">
                              <strong>{{ $message }}</strong>
                          </span>
                          @enderror
                      </div>
                  </div>
                  
                  <div class="form-group row" >

                      <div class="col-md-10 offset-md-1">
                          <input id="password" type="password" name="password" class="form-control @error('password') is-invalid @enderror"  required autocomplete="current-password" placeholder="Password">
                          
                          @error('password')
                          <span class="invalid-feedback" role="alert">
                                  <strong>{{ $message }}</strong>
                              </span>
                              @enderror
                          </div>
                      </div>
                      
                      <div class="form-group row mb-0">
                          <div class="col-md-10 offset-md-1 mt-3">
                              <button type="submit" class="btn btn-primary btn-user btn-block">
                                  {{ __('Login') }}
                              </button>
                      </div>
                  </div>
              </div>
          </div>
                <div class="my-2 d-flex justify-content-between align-items-center">
                  <div class="form-check">
                    <label class="form-check-label text-muted">
                      <input type="checkbox" class="form-check-input">
                      Keep me signed in
                    </label>
                  </div>
                  <a href="#" class="auth-link text-black">Forgot password?</a>
                </div>
                <div class="mb-2">
                  <button type="button" class="btn btn-block btn-facebook auth-form-btn">
                    <i class="ti-facebook me-2"></i>Connect using facebook
                  </button>
                </div>
                <div class="text-center mt-4 fw-light">
                  Don't have an account? <a href="register" class="text-primary">Create</a>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
      <!-- content-wrapper ends -->
    </div>
    <!-- page-body-wrapper ends -->
  </div>
  <!-- container-scroller -->
  <!-- plugins:js -->
  <script src="assets/vendors/js/vendor.bundle.base.js"></script>
  <!-- endinject -->
  <!-- Plugin js for this page -->
  <script src="assets/vendors/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>
  <!-- End plugin js for this page -->
  <!-- inject:js -->
  <script src="assets/js/off-canvas.js"></script>
  <script src="assets/js/hoverable-collapse.js"></script>
  <script src="assets/js/template.js"></script>
  <script src="assets/js/settings.js"></script>
  <script src="assets/js/todolist.js"></script>
  <!-- endinject -->
</body>

</html> --}}

resources/views/tambahtamu.blade.php
@extends('layouts.main')
@section('content')
<div class="main-panel">        
    <div class="content-wrapper">
      <div class="row">
        <div class="col-md-6 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <h4 class="card-title">Tambah Data Tamu</h4>
              <form action="{{ route('tambahtamu.store') }}"  method="POST">
                @csrf
              <form class="forms-sample">
                <div class="form-group">
                  <label for="nama">Nama</label>
                  <input type="string" class="form-control" id="nama" name="nama" placeholder="Nama">
                </div>
                <div class="form-group">
                  <label for="alamat">Alamat</label>
                  <input type="string" class="form-control" id="alamat" name="alamat"placeholder="Alamat">
                </div>
                <div class="form-group">
                  <label for="no_hp">NO HP</label>
                  <input type="char" class="form-control" id="no_hp" name="no_hp"placeholder="NO HP">
                </div>
                <div class="form-group">
                  <label for="tgl">Tanggal</label>
                  <input type="date" class="form-control" id="tgl" name="tgl"placeholder="tgl">
                </div>
                <button type="submit" class="btn btn-primary me-2">Simpan</button>
                <button class="btn btn-light">Cancel</button>
              </form>
            </div>
          </div>
        </div>
@endsection

resources/views/thutangberas.blade.php
@extends('layouts.main')
@section('content')
<div class="main-panel">        
    <div class="content-wrapper">
      <div class="row">
        <div class="col-md-6 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <h4 class="card-title">Tambah Magang Padi</h4>
              <form action=""  method="POST">
                @csrf
              <form class="forms-sample">
                <div class="form-group">
                    <label >Nama</label>
                    <select name ="data_tamu_id" class="form-control" >
                 
                      <option value=""> Pilih </option>
                      @foreach ($data_tamu as $tamu)
                      <option value="{{ $tamu->id }}"> {{ $tamu->nama}}</option>
                          
                      @endforeach
                    
                     
                    </select>
                  </div>
                <div class="form-group">
                  <label for="nama">Nominal</label>
                  <input type="string" class="form-control" id="nama" name="nama" placeholder="Nama">
                </div>

                <button type="submit" class="btn btn-primary me-2">Simpan</button>
                <button class="btn btn-light">Cancel</button>
              </form>
            </div>
          </div>
        </div>
@endsection

resources/views/thutangpadi.blade.php
@extends('layouts.main')
@section('content')
<div class="main-panel">        
    <div class="content-wrapper">
      <div class="row">
        <div class="col-md-6 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <h4 class="card-title">Tambah Magang Padi</h4>
              <form action=""  method="POST">
                @csrf
              <form class="forms-sample">
                <div class="form-group">
                    <label >Nama</label>
                    <select name ="data_tamu_id" class="form-control" >
                 
                      <option value=""> Pilih </option>
                      @foreach ($data_tamu as $tamu)
                      <option value="{{ $tamu->id }}"> {{ $tamu->nama}}</option>
                          
                      @endforeach
                    
                     
                    </select>
                  </div>
                <div class="form-group">
                  <label for="nama">Nominal</label>
                  <input type="string" class="form-control" id="nama" name="nama" placeholder="Nama">
                </div>

                <button type="submit" class="btn btn-primary me-2">Simpan</button>
                <button class="btn btn-light">Cancel</button>
              </form>
            </div>
          </div>
        </div>
@endsection

resources/views/thutanguang.blade.php
@extends('layouts.main')
@section('content')
<div class="main-panel">        
    <div class="content-wrapper">
      <div class="row">
        <div class="col-md-6 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <h4 class="card-title">Tambah Magang Uang</h4>
              <form action=""  method="POST">
                @csrf
              <form class="forms-sample">
                <div class="form-group">
                    <label >Nama</label>
                    <select name ="data_tamu_id" class="form-control" >
                 
                      <option value=""> Pilih </option>
                      @foreach ($data_tamu as $tamu)
                      <option value="{{ $tamu->id }}"> {{ $tamu->nama}}</option>
                          
                      @endforeach
                    
                     
                    </select>
                  </div>
                <div class="form-group">
                  <label for="nama">Nominal</label>
                  <input type="string" class="form-control" id="nama" name="nama" placeholder="Nama">
                </div>

                <button type="submit" class="btn btn-primary me-2">Simpan</button>
                <button class="btn btn-light">Cancel</button>
              </form>
            </div>
          </div>
        </div>
@endsection

resources/views/tkeluarpadi.blade.php
@extends('layouts.main')
@section('content')
<div class="main-panel">        
    <div class="content-wrapper">
      <div class="row">
        <div class="col-md-6 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <h4 class="card-title">Tambah Magang Padi</h4>
              <form action="{{ route('tkeluarpadi.store') }}"  method="POST">
                @csrf
              <form class="forms-sample">
                <div class="form-group">
                  <label for="nama">Nama</label>
                  <input type="string" class="form-control" id="nama" name="nama" placeholder="Nama">
                </div>
                <div class="form-group">
                  <label for="alamat">Alamat</label>
                  <input type="string" class="form-control" id="alamat" name="alamat"placeholder="Alamat">
                </div>
                <div class="form-group">
                  <label for="no_hp">NO HP</label>
                  <input type="char" class="form-control" id="no_hp" name="no_hp"placeholder="NO HP">
                </div>
                <div class="form-group">
                  <label for="tgl">Tanggal</label>
                  <input type="date" class="form-control" id="tgl" name="tgl"placeholder="tgl">
                </div>
                <div class="form-group">
                  <label for="tgl">Nominal</label>
                  <input type="int" class="form-control" id="nominal" name="nominal"placeholder="nominal">
                </div>
                <button type="submit" class="btn btn-primary me-2">Simpan</button>
                <button class="btn btn-light">Cancel</button>
              </form>
            </div>
          </div>
        </div>
@endsection

resources/views/tmagangberas.blade.php
@extends('layouts.main')
@section('content')
<div class="main-panel">        
    <div class="content-wrapper">
      <div class="row">
        <div class="col-md-6 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <h4 class="card-title">Tambah Magang Beras</h4>
              <form action=""  method="POST">
                @csrf
              <form class="forms-sample">
                <div class="form-group">
                    <label >Nama</label>
                    <select name ="data_tamu_id" class="form-control" >
                 
                      <option value=""> Pilih </option>
                      @foreach ($data_tamu as $tamu)
                      <option value="{{ $tamu->id }}"> {{ $tamu->nama}}</option>
                        
                      @endforeach
                    
                     
                    </select>
                  </div>
                <div class="form-group">
                  <label for="nama">Nominal</label>
                  <input type="string" class="form-control" id="nama" name="nama" placeholder="Kg">
                </div>

                <button type="submit" class="btn btn-primary me-2">Simpan</button>
                <button class="btn btn-light">Cancel</button>
              </form>
            </div>
          </div>
        </div>
@endsection

resources/views/tmagangpadi.blade.php
@extends('layouts.main')
@section('content')
<div class="main-panel">        
    <div class="content-wrapper">
      <div class="row">
        <div class="col-md-6 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <h4 class="card-title">Tambah Magang Padi</h4>
              <form action=""  method="POST">
                @csrf
              <form class="forms-sample">
                <div class="form-group">
                    <label >Nama</label>
                    <select name ="data_tamu_id" class="form-control" >
                 
                      <option value=""> Pilih </option>
                      @foreach ($data_tamu as $tamu)
                      <option value="{{ $tamu->id }}"> {{ $tamu->nama}}</option>
                          
                      @endforeach
                    
                     
                    </select>
                  </div>
                <div class="form-group">
                  <label for="nama">Nominal</label>
                  <input type="string" class="form-control" id="nama" name="nama" placeholder="Kg">
                </div>

                <button type="submit" class="btn btn-primary me-2">Simpan</button>
                <button class="btn btn-light">Cancel</button>
              </form>
            </div>
          </div>
        </div>
@endsection

resources/views/tmaganguang.blade.php
@extends('layouts.main')
@section('content')
<div class="main-panel">        
    <div class="content-wrapper">
      <div class="row">
        <div class="col-md-6 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <h4 class="card-title">Tambah Magang Uang</h4>
              <form action=""  method="POST">
                @csrf
              <form class="forms-sample">
                <div class="form-group">
                    <label >Nama</label>
                    <select name ="data_tamu_id" class="form-control" >
                 
                      <option value=""> Pilih </option>
                      @foreach ($data_tamu as $tamu)
                      <option value="{{ $tamu->id }}"> {{ $tamu->nama}}</option>
                          
                      @endforeach
                    
                     
                    </select>
                  </div>
                <div class="form-group">
                  <label for="nama">Nominal</label>
                  <input type="string" class="form-control" id="nama" name="nama" placeholder="Rupiah">
                </div>

                <button type="submit" class="btn btn-primary me-2">Simpan</button>
                <button class="btn btn-light">Cancel</button>
              </form>
            </div>
          </div>
        </div>
@endsection