routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('landing');
});
Route::get('admin', function () {
    return view('admin2/admin-home');
});
Route::get('admin-hajatan', function () {
    return view('admin2/admin-hajatan');
});
Route::get('admin-chat', function () {
    return view('admin2/admin-chat');
});
// Route::get('/coba', function () {
//     return view('coba');
// });
// Route::get('/home', function () {
//     return view('home');
// });
// Route::get('/login', function () {
//     return view('login');
// });
Route::get('/register', function () {
    return view('register');
});
Route::get('/tmagangpadi', function () {
    return view('tmagangpadi');
});
Route::get('/tmaganguang', function () {
    return view('tmaganguang');
});
// Route::get('/tmagangberas', function () {
//     return view('tmagangberas');
// });
Route::get('/thutangberas', function () {
    return view('tmaganguang');
});
Route::get('/thutangpadi', function () {
    return view('thutangpadi');
});
Route::get('/thutanguang', function () {
    return view('thutanguang');
});
// Route::get('/tkeluarberas', function () {
//     return view('tkeluarberas');
// });
// Route::get('/tkeluarpadi', function () {
//     return view('tkeluarpadi');
// });
Route::get('/tkeluaruang', function () {
    return view('tkeluaruang');
});
// Route::resource('input', DataTamuController::class);

Route::get('/magangberas', function () {
    return view('Anggota/m_beras');
});
Route::get('/magangpadi', function () {
    return view('Anggota/m_padi');
});
Route::get('/maganguang', function () {
    return view('Anggota/m_uang');
});
Route::get('/hutangberas', function () {
    return view('Anggota/h_beras');
});
Route::get('/hutangpadi', function () {
    return view('Anggota/h_padi');
});
Route::get('/hutanguang', function () {
    return view('Anggota/h_uang');
});
// Route::get('/keluarberas', function () {
//     return view('Anggota/k_beras');
// });
// Route::get('/keluarpadi', function () {
//     return view('Anggota/k_padi');
// });
// Route::get('/k_uang', function () {
//     return view('Anggota/k_uang');
// });
Route::get('/chat', function () {
    return view('Anggota/chat');
});



Route::resource('tambahtamu', 'DataTamuController');
Route::resource('home', 'DataTamu2Controller');
// Route::resource('edit', 'DataTamu2Controller');
Route::resource('edittamu', 'DataTamu2Controller');
Route::resource('tkeluarberas', 'MagangKeluarBerasController');
Route::resource('tkeluarpadi', 'MagangKeluarPadiController');
Route::resource('tkeluaruang', 'MagangKeluarUangController');
Route::resource('k_beras', 'ReadMagangBerasController');
Route::resource('k_padi', 'ReadMagangPadiController');
Route::resource('k_uang', 'ReadMagangUangController');
Route::resource('editmagangberas', 'MagangKeluarBerasController');
Route::resource('editmagangpadi', 'MagangKeluarPadiController');
Route::resource('editmaganguang', 'MagangKeluarUangController');
Route::resource('tmagangberas', 'TambahMagangBerasController');
Route::resource('tmagangpadi', 'TambahMagangPadiController');
Route::resource('tmaganguang', 'TambahMagangUangController');
Route::resource('thutangberas', 'TambahHutangBerasController');
Route::resource('thutangpadi', 'TambahHutangPadiController');
Route::resource('thutanguang', 'TambahHutangUangController');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/Anggota/chat.blade.php
@extends('layouts.main')
@section('content')
<div class="main-panel">
    <div class="content-wrapper">
      <div class="row">
        <div class="col-lg-6 grid-margin stretch-card">
          <div class="card">
          </div>
        </div>
        <div class="col-lg-12 grid-margin stretch-card">
          <div class="card" >
            <div class="card-body" style="overflow-x:auto;">
              <h4 class="card-title">CHAT</h4>
              
           
            </div>
          </div>
        </div>
        <div class="col-lg-12 grid-margin stretch-card">
          <div class="card">
           
          </div>
        </div>
        <div class="col-lg-12 stretch-card">
        
        </div>
      </div>
    </div>
    <!-- content-wrapper ends -->
    <!-- partial:../../partials/_footer.html -->
    <footer class="footer">
      <div class="d-sm-flex justify-content-center justify-content-sm-between">
                <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Copyright © 2021. All rights reserved.</span>
      </div>
    </footer>
    <!-- partial -->
  </div>
  @endsection

  

resources/views/Anggota/edittamu.blade.php
@extends('layouts.main')
@section('content')
<div class="main-panel">        
    <div class="content-wrapper">
      <div class="row">
        <div class="col-md-6 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <h4 class="card-title">Edit Data Tamu</h4>
              <form action="{{ route('edittamu.update', $datatamu->id) }}"  method="POST">
                @csrf
                @method('PUT')
              <form class="forms-sample">
                <div class="form-group">
                  <label for="nama">Nama</label>
                  <input type="string" class="form-control" id="nama" name="nama" value="<?php echo $datatamu['nama']; ?>" placeholder="Nama">
                </div>
                <div class="form-group">
                  <label for="alamat">Alamat</label>
                  <input type="string" class="form-control" id="alamat" name="alamat" value="<?php echo $datatamu['alamat']; ?>"placeholder="Alamat">
                </div>
                <div class="form-group">
                  <label for="no_hp">NO HP</label>
                  <input type="char" class="form-control" id="no_hp" name="no_hp" value="<?php echo $datatamu['no_hp']; ?>"placeholder="NO HP">
                </div>
                <div class="form-group">
                  <label for="tgl">Tanggal</label>
                  <input type="date" class="form-control" id="tgl" name="tgl" value="<?php echo $datatamu['tgl']; ?>"placeholder="tgl">
                </div>
                <button type="submit" class="btn btn-primary me-2">Simpan</button>
                <button class="btn btn-light">Cancel</button>
              </form>
            </div>
          </div>
        </div>
@endsection

resources/views/Anggota/h_beras.blade.php
@extends('layouts.main')
@section('content')
<div class="main-panel">
    <div class="content-wrapper">
      <div class="row">
        <div class="col-lg-6 grid-margin stretch-card">
          <div class="card">
          </div>
        </div>
        <div class="col-lg-12 grid-margin stretch-card">
          <div class="card" >
            <div class="card-body" style="overflow-x:auto;">
              <h4 class="card-title">DATA PEMASUKAN HUTANG BERAS</h4>
              <a href="thutangberas" class="btn btn-primary btn-sm"><i class="fas fa-plus"></i> Tambah Hutang Beras</a>
              <a href="/tambahtamu" class="btn btn-primary btn-sm"><i class="fas fa-plus"></i> Cetak PDF</a>
              <table id="example" class="table table-striped table-bordered nowrap " style="width:100%">
                <thead>
                    <tr>
                        <th>NO</th>
                        <th>NAMA</th>
                        <th>ALAMAT</th>
                        <th>NO HP</th>
                        <th>NOMINAL</th>
                        <th>TANGGAL</th>
                        <th>AKSI</th>
                    </tr>
                </thead>
                <tbody>
                  
                   
                </tbody>
            </table>
            </div>
          </div>
        </div>
        <div class="col-lg-12 grid-margin stretch-card">
          <div class="card">
           
          </div>
        </div>
        <div class="col-lg-12 stretch-card">
        
        </div>
      </div>
    </div>
    <!-- content-wrapper ends -->
    <!-- partial:../../partials/_footer.html -->
    <footer class="footer">
      <div class="d-sm-flex justify-content-center justify-content-sm-between">
                <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Copyright © 2021. All rights reserved.</span>
      </div>
    </footer>
    <!-- partial -->
  </div>
  @endsection

  

resources/views/Anggota/h_padi.blade.php
@extends('layouts.main')
@section('content')
<div class="main-panel">
    <div class="content-wrapper">
      <div class="row">
        <div class="col-lg-6 grid-margin stretch-card">
          <div class="card">
          </div>
        </div>
        <div class="col-lg-12 grid-margin stretch-card">
          <div class="card" >
            <div class="card-body" style="overflow-x:auto;">
              <h4 class="card-title">DATA PEMASUKAN HUTANG PADI</h4>
              <a href="thutangpadi" class="btn btn-primary btn-sm"><i class="fas fa-plus"></i> Tambah Hutang Padi</a>
              <a href="/tambahtamu" class="btn btn-primary btn-sm"><i class="fas fa-plus"></i> Cetak PDF</a>
              <table id="example" class="table table-striped table-bordered nowrap " style="width:100%">
                <thead>
                    <tr>
                        <th>NO</th>
                        <th>NAMA</th>
                        <th>ALAMAT</th>
                        <th>NO HP</th>
                        <th>NOMINAL</th>
                        <th>TANGGAL</th>
                        <th>AKSI</th>
                    </tr>
                </thead>
                <tbody>
                   
                   
                </tbody>
            </table>
            </div>
          </div>
        </div>
        <div class="col-lg-12 grid-margin stretch-card">
          <div class="card">
           
          </div>
        </div>
        <div class="col-lg-12 stretch-card">
        
        </div>
      </div>
    </div>
    <!-- content-wrapper ends -->
    <!-- partial:../../partials/_footer.html -->
    <footer class="footer">
      <div class="d-sm-flex justify-content-center justify-content-sm-between">
                <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Copyright © 2021. All rights reserved.</span>
      </div>
    </footer>
    <!-- partial -->
  </div>
  @endsection

  

resources/views/Anggota/h_uang.blade.php
@extends('layouts.main')
@section('content')
<div class="main-panel">
    <div class="content-wrapper">
      <div class="row">
        <div class="col-lg-6 grid-margin stretch-card">
          <div class="card">
          </div>
        </div>
        <div class="col-lg-12 grid-margin stretch-card">
          <div class="card" >
            <div class="card-body" style="overflow-x:auto;">
              <h4 class="card-title">DATA PEMASUKAN HUTANG UANG</h4>
              <a href="thutanguang" class="btn btn-primary btn-sm"><i class="fas fa-plus"></i> Tambah Hutang Uang</a>
              <a href="/tambahtamu" class="btn btn-primary btn-sm"><i class="fas fa-plus"></i> Cetak PDF</a>
              <table id="example" class="table table-striped table-bordered nowrap " style="width:100%">
                <thead>
                    <tr>
                        <th>NO</th>
                        <th>NAMA</th>
                        <th>ALAMAT</th>
                        <th>NO HP</th>
                        <th>NOMINAL</th>
                        <th>TANGGAL</th>
                        <th>AKSI</th>
                    </tr>
                </thead>
                <tbody>
                   
                   
                </tbody>
            </table>
            </div>
          </div>
        </div>
        <div class="col-lg-12 grid-margin stretch-card">
          <div class="card">
           
          </div>
        </div>
        <div class="col-lg-12 stretch-card">
        
        </div>
      </div>
    </div>
    <!-- content-wrapper ends -->
    <!-- partial:../../partials/_footer.html -->
    <footer class="footer">
      <div class="d-sm-flex justify-content-center justify-content-sm-between">
                <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Copyright © 2021. All rights reserved.</span>
      </div>
    </footer>
    <!-- partial -->
  </div>
  @endsection

  

resources/views/Anggota/home.blade.php
@extends('layouts.main')
@section('content')
<div class="main-panel">
    <div class="content-wrapper">
      <div class="row">
        <div class="col-lg-6 grid-margin stretch-card">
          <div class="card">
          </div>
        </div>
        <div class="col-lg-12 grid-margin stretch-card">
          <div class="card" >
            <div class="card-body" style="overflow-x:auto;">
              <h4 class="card-title">DATA TAMU</h4>
              <a href="/tambahtamu" class="btn btn-primary btn-sm"><i class="fas fa-plus"></i> Tambah Tamu</a>
              <a href="" class="btn btn-primary btn-sm"><i class="fas fa-plus"></i> Cetak PDF</a>
            <table id="example" class="table table-striped table-bordered nowrap " style="width:100%">
                <thead>
                  <tr>
                        <th>NO</th>
                        <th>NAMA</th>
                        <th>ALAMAT</th>
                        <th>NO HP</th>
                        <th>TANGGAL</th>
                        <th>AKSI</th>
                    </tr>
                </thead>
              <tbody>

                @foreach ($data_tamu as $tamu)
                <tr>
                  <th scope="row">{{$loop->iteration}}</th>
                  <td>{{ $tamu ->nama}}</td>
                  <td>{{ $tamu ->alamat}}</td>
                  <td>{{ $tamu ->no_hp}}</td>
                  <td>{{ $tamu ->tgl}}</td>

                  <td>
        
    
                    <div class="btn-group" role="group" aria-label="Basic example">
                      <a href="{{route('edittamu.edit', $tamu->id) }}" class="btn btn-primary btn-sm mr-1"><i class="fas fa-edit"></i> Edit</a>
                      
                      <form action="{{route('home.destroy', $tamu->id) }}" method="POST">
                        @method('DELETE')
                        @csrf
                        <button type="submit" class="btn btn-danger btn-sm"><i class="fas fa-trash"></i> Hapus</button>
                      </form>
                      </div>
                    </td>
                </tr>
                    
                @endforeach  
                   
              </tbody>
            </table>
            </div>
          </div>
        </div>
        <div class="col-lg-12 grid-margin stretch-card">
          <div class="card">
           
          </div>
        </div>
        <div class="col-lg-12 stretch-card">
        
        </div>
      </div>
    </div>
    <!-- content-wrapper ends -->
    <!-- partial:../../partials/_footer.html -->
    <footer class="footer">
      <div class="d-sm-flex justify-content-center justify-content-sm-between">
                <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Copyright © 2021. All rights reserved.</span>
      </div>
    </footer>
    <!-- partial -->
  </div>
  @endsection

  

resources/views/Anggota/k_beras.blade.php
@extends('layouts.main')
@section('content')
<div class="main-panel">
    <div class="content-wrapper">
      <div class="row">
        <div class="col-lg-6 grid-margin stretch-card">
          <div class="card">
          </div>
        </div>
        <div class="col-lg-12 grid-margin stretch-card">
          <div class="card" >
            <div class="card-body" style="overflow-x:auto;">
              <h4 class="card-title">DATA PENGELUARAN MAGANG BERAS</h4>
              <a href="/tkeluarberas" class="btn btn-primary btn-sm"><i class="fas fa-plus"></i> Tambah Pengeluaran</a>
              <a href="/tambahtamu" class="btn btn-primary btn-sm"><i class="fas fa-plus"></i> Cetak PDF</a>
              <table id="example" class="table table-striped table-bordered nowrap " style="width:100%">
                <thead>
                    <tr>
                        <th>NO</th>
                        <th>NAMA</th>
                        <th>ALAMAT</th>
                        <th>NO HP</th>
                        <th>NOMINAL (Kg)</th>
                        <th>TANGGAL</th>
                        <th>AKSI</th>
                    </tr>
                </thead>
                <tbody>
                   
                  @foreach ($keluar_magang_beras as $beras)
                  <tr>
                    <th scope="row">{{$loop->iteration}}</th>
                    <td>{{ $beras ->nama}}</td>
                    <td>{{ $beras ->alamat}}</td>
                    <td>{{ $beras ->no_hp}}</td>
                    <td>{{ $beras ->nominal}}</td>
                    <td>{{ $beras ->tgl}}</td>
  
                    <td>
          
      
                      <div class="btn-group" role="group" aria-label="Basic example">
                        <a href="{{route('editmagangberas.edit', $beras->id) }}" class="btn btn-primary btn-sm mr-1"><i class="fas fa-edit"></i> Edit</a>
                        
                        <form action="{{route('tkeluarberas.destroy', $beras->id) }}" method="POST">
                          @method('DELETE')
                          @csrf
                          <button type="submit" class="btn btn-danger btn-sm"><i class="fas fa-trash"></i> Hapus</button>
                        </form>
                        <form action="">
                          
                          <button type="submit" class="btn btn-danger btn-sm"><i class="fas fa-trash"></i> Notifikasi</button>
                        </form>
                        </div>
                      </td>
                  </tr>
                      
                  @endforeach  
                </tbody>
            </table>
            </div>
          </div>
        </div>
        <div class="col-lg-12 grid-margin stretch-card">
          <div class="card">
           
          </div>
        </div>
        <div class="col-lg-12 stretch-card">
        
        </div>
      </div>
    </div>
    <!-- content-wrapper ends -->
    <!-- partial:../../partials/_footer.html -->
    <footer class="footer">
      <div class="d-sm-flex justify-content-center justify-content-sm-between">
                <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Copyright © 2021. All rights reserved.</span>
      </div>
    </footer>
    <!-- partial -->
  </div>
  @endsection

  

resources/views/Anggota/k_padi.blade.php
@extends('layouts.main')
@section('content')
<div class="main-panel">
    <div class="content-wrapper">
      <div class="row">
        <div class="col-lg-6 grid-margin stretch-card">
          <div class="card">
          </div>
        </div>
        <div class="col-lg-12 grid-margin stretch-card">
          <div class="card" >
            <div class="card-body" style="overflow-x:auto;">
              <h4 class="card-title">DATA PENGELUARAN MAGANG PADI</h4>
              <a href="/tkeluarpadi" class="btn btn-primary btn-sm"><i class="fas fa-plus"></i> Tambah Pengeluaran</a>
              <a href="/tambahtamu" class="btn btn-primary btn-sm"><i class="fas fa-plus"></i> Cetak PDF</a>
              <table id="example" class="table table-striped table-bordered nowrap " style="width:100%">
                <thead>
                    <tr>
                        <th>NO</th>
                        <th>NAMA</th>
                        <th>ALAMAT</th>
                        <th>NO HP</th>
                        <th>NOMINAL (Kg)</th>
                        <th>TANGGAL</th>
                        <th>AKSI</th>
                    </tr>
                </thead>
                <tbody>
                   
                  @foreach ($keluar_magang_padi as $padi)
                  <tr>
                    <th scope="row">{{$loop->iteration}}</th>
                    <td>{{ $padi ->nama}}</td>
                    <td>{{ $padi ->alamat}}</td>
                    <td>{{ $padi ->no_hp}}</td>
                    <td>{{ $padi ->nominal}}</td>
                    <td>{{ $padi ->tgl}}</td>
  
                    <td>
          
      
                      <div class="btn-group" role="group" aria-label="Basic example">
                        <a href="{{route('editmagangpadi.edit', $padi->id) }}" class="btn btn-primary btn-sm mr-1"><i class="fas fa-edit"></i> Edit</a>
                        
                        <form action="{{route('tkeluarpadi.destroy', $padi->id) }}" method="POST">
                          @method('DELETE')
                          @csrf
                          <button type="submit" class="btn btn-danger btn-sm"><i class="fas fa-trash"></i> Hapus</button>
                        </form>
                        </div>
                    </td>
                  </tr>
                      
                  @endforeach  
                </tbody>
            </table>
            </div>
          </div>
        </div>
        <div class="col-lg-12 grid-margin stretch-card">
          <div class="card">
           
          </div>
        </div>
        <div class="col-lg-12 stretch-card">
        
        </div>
      </div>
    </div>
    <!-- content-wrapper ends -->
    <!-- partial:../../partials/_footer.html -->
    <footer class="footer">
      <div class="d-sm-flex justify-content-center justify-content-sm-between">
                <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Copyright © 2021. All rights reserved.</span>
      </div>
    </footer>
    <!-- partial -->
  </div>
  @endsection

  

resources/views/Anggota/k_uang.blade.php
@extends('layouts.main')
@section('content')
<div class="main-panel">
    <div class="content-wrapper">
      <div class="row">
        <div class="col-lg-6 grid-margin stretch-card">
          <div class="card">
          </div>
        </div>
        <div class="col-lg-12 grid-margin stretch-card">
          <div class="card" >
            <div class="card-body" style="overflow-x:auto;">
              <h4 class="card-title">DATA PENGELUARAN MAGANG UANG</h4>
              <a href="tkeluaruang" class="btn btn-primary btn-sm"><i class="fas fa-plus"></i> Tambah Pengeluaran</a>
              <a href="/tambahtamu" class="btn btn-primary btn-sm"><i class="fas fa-plus"></i> Cetak PDF</a>
              <table id="example" class="table table-striped table-bordered nowrap " style="width:100%">
                <thead>
                    <tr>
                        <th>NO</th>
                        <th>NAMA</th>
                        <th>ALAMAT</th>
                        <th>NO HP</th>
                        <th>NOMINAL (Rupiah)</th>
                        <th>TANGGAL</th>
                        <th>AKSI</th>
                    </tr>
                </thead>
                <tbody>
                  @foreach ($keluar_magang_uang as $uang)
                  <tr>
                    <th scope="row">{{$loop->iteration}}</th>
                    <td>{{ $uang ->nama}}</td>
                    <td>{{ $uang ->alamat}}</td>
                    <td>{{ $uang ->no_hp}}</td>
                    <td>{{ $uang ->nominal}}</td>
                    <td>{{ $uang ->tgl}}</td>
  
                    <td>
          
      
                      <div class="btn-group" role="group" aria-label="Basic example">
                        <a href="{{route('editmaganguang.edit', $uang->id) }}" class="btn btn-primary btn-sm mr-1"><i class="fas fa-edit"></i> Edit</a>
                        
                        <form action="{{route('tkeluaruang.destroy', $uang->id) }}" method="POST">
                          @method('DELETE')
                          @csrf
                          <button type="submit" class="btn btn-danger btn-sm"><i class="fas fa-trash"></i> Hapus</button>
                        </form>
                        </div>
                    </td>
                  </tr>
                      
                  @endforeach  
                </tbody>
            </table>
            </div>
          </div>
        </div>
        <div class="col-lg-12 grid-margin stretch-card">
          <div class="card">
           
          </div>
        </div>
        <div class="col-lg-12 stretch-card">
        
        </div>
      </div>
    </div>
    <!-- content-wrapper ends -->
    <!-- partial:../../partials/_footer.html -->
    <footer class="footer">
      <div class="d-sm-flex justify-content-center justify-content-sm-between">
                <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Copyright © 2021. All rights reserved.</span>
      </div>
    </footer>
    <!-- partial -->
  </div>
  @endsection

  

resources/views/Anggota/m_beras.blade.php
@extends('layouts.main')
@section('content')
<div class="main-panel">
    <div class="content-wrapper">
      <div class="row">
        <div class="col-lg-6 grid-margin stretch-card">
          <div class="card">
          </div>
        </div>
        <div class="col-lg-12 grid-margin stretch-card">
          <div class="card" >
            <div class="card-body" style="overflow-x:auto;">
              <h4 class="card-title">DATA PEMASUKAN MAGANG BERAS</h4>
              <a href="/tmagangberas" class="btn btn-primary btn-sm"><i class="fas fa-plus"></i> Tambah Magang Beras</a>
              <a href="" class="btn btn-primary btn-sm"><i class="fas fa-plus"></i> Cetak PDF</a>
              <table id="example" class="table table-striped table-bordered nowrap " style="width:100%">
                <thead>
                    <tr>
                        <th>NO</th>
                        <th>NAMA</th>
                        <th>ALAMAT</th>
                        <th>NO HP</th>
                        <th>NOMINAL</th>
                        <th>TANGGAL</th>
                        <th>AKSI</th>
                    </tr>
                </thead>
                <tbody>
                   
                   
                </tbody>
            </table>
            </div>
          </div>
        </div>
        <div class="col-lg-12 grid-margin stretch-card">
          <div class="card">
           
          </div>
        </div>
        <div class="col-lg-12 stretch-card">
        
        </div>
      </div>
    </div>
    <!-- content-wrapper ends -->
    <!-- partial:../../partials/_footer.html -->
    <footer class="footer">
      <div class="d-sm-flex justify-content-center justify-content-sm-between">
                <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Copyright © 2021. All rights reserved.</span>
      </div>
    </footer>
    <!-- partial -->
  </div>
  @endsection

  

resources/views/Anggota/m_padi.blade.php
@extends('layouts.main')
@section('content')
<div class="main-panel">
    <div class="content-wrapper">
      <div class="row">
        <div class="col-lg-6 grid-margin stretch-card">
          <div class="card">
          </div>
        </div>
        <div class="col-lg-12 grid-margin stretch-card">
          <div class="card" >
            <div class="card-body" style="overflow-x:auto;">
              <h4 class="card-title">DATA PEMASUKAN MAGANG PADI</h4>
              
              <a href="/tmagangpadi" class="btn btn-primary btn-sm"><i class="fas fa-plus"></i> Tambah Magang Padi</a>
              <a href="/tambahtamu" class="btn btn-primary btn-sm"><i class="fas fa-plus"></i> Cetak PDF</a>
              <table id="example" class="table table-striped table-bordered nowrap " style="width:100%">
                <thead>
                    <tr>
                        <th>NO</th>
                        <th>NAMA</th>
                        <th>ALAMAT</th>
                        <th>NO HP</th>
                        <th>NOMINAL</th>
                        <th>TANGGAL</th>
                        <th>AKSI</th>
                    </tr>
                </thead>
                <tbody>
                   
                   
                </tbody>
            </table>
            </div>
          </div>
        </div>
        <div class="col-lg-12 grid-margin stretch-card">
          <div class="card">
           
          </div>
        </div>
        <div class="col-lg-12 stretch-card">
        
        </div>
      </div>
    </div>
    <!-- content-wrapper ends -->
    <!-- partial:../../partials/_footer.html -->
    <footer class="footer">
      <div class="d-sm-flex justify-content-center justify-content-sm-between">
                <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Copyright © 2021. All rights reserved.</span>
      </div>
    </footer>
    <!-- partial -->
  </div>
  @endsection

  

resources/views/Anggota/m_uang.blade.php
@extends('layouts.main')
@section('content')
<div class="main-panel">
    <div class="content-wrapper">
      <div class="row">
        <div class="col-lg-6 grid-margin stretch-card">
          <div class="card">
          </div>
        </div>
        <div class="col-lg-12 grid-margin stretch-card">
          <div class="card" >
            <div class="card-body" style="overflow-x:auto;">
             
              <h4 class="card-title">DATA PEMASUKAN MAGANG UANG</h4>
              <a href="tmaganguang" class="btn btn-primary btn-sm"><i class="fas fa-plus"></i> Tambah Magang Uang</a>
              <a href="/tambahtamu" class="btn btn-primary btn-sm"><i class="fas fa-plus"></i> Cetak PDF</a>
              <table id="example" class="table table-striped table-bordered nowrap " style="width:100%">
                <thead>
                    <tr>
                        <th>NO</th>
                        <th>NAMA</th>
                        <th>ALAMAT</th>
                        <th>NO HP</th>
                        <th>NOMINAL</th>
                        <th>TANGGAL</th>
                        <th>AKSI</th>
                    </tr>
                </thead>
                <tbody>
                   
                   
                </tbody>
            </table>
            </div>
          </div>
        </div>
        <div class="col-lg-12 grid-margin stretch-card">
          <div class="card">
           
          </div>
        </div>
        <div class="col-lg-12 stretch-card">
        
        </div>
      </div>
    </div>
    <!-- content-wrapper ends -->
    <!-- partial:../../partials/_footer.html -->
    <footer class="footer">
      <div class="d-sm-flex justify-content-center justify-content-sm-between">
                <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Copyright © 2021. All rights reserved.</span>
      </div>
    </footer>
    <!-- partial -->
  </div>
  @endsection

  